#!/bin/sh

# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.

jenkins_url()
{
    url="$(snapctl get jenkins.url)"
    if [ -z "$url" ]; then
        echo "unset"
    fi
    echo "$url"
}

set_jenkins_url()
{
    snapctl set jenkins.url="$1"
}

jenkins_agent()
{
    agent="$(snapctl get jenkins.agent)"
    if [ -z "$agent" ]; then
        echo "unset"
    fi
    echo "$agent"
}

set_jenkins_agent()
{
    snapctl set jenkins.agent="$1"
}

jenkins_token()
{
    tk="$(snapctl get jenkins.token)"
    if [ -z "$tk" ]; then
        echo "unset"
    fi
    echo "$tk"
}

set_jenkins_token()
{
    snapctl set jenkins.token="$1"
}
