# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.

name: jenkins-agent
summary: Jenkins agent snap
description: Agent for jenkins
version: "1.0.0"
base: core22
license: Apache-2.0
confinement: classic
apps:
  jenkins-agent:
    command: "bin/agent.start"
    daemon: simple
    environment:
      JAVA_HOME: $SNAP/bin/jdk
      PATH: $JAVA_HOME/bin:$SNAP/bin/usr/bin:$PATH
    plugs:
      - "network"
      - "home"
parts:
  part-jenkins-agent:
    stage-snaps:
      - openjdk
    plugin: dump
    override-prime: |
      snapcraftctl prime
      ls -la $SNAPCRAFT_PRIME
    source: commands
    organize:
      '*': bin/

  hooks:
    plugin: dump
    source: hooks
    organize:
      '*': snap/hooks/

  scripts:
    plugin: dump
    source: scripts
    organize:
      '*': bin/

  bash-utils:
    plugin: nil
    stage-packages:
      - curl
      - git
    # stage-snaps:
    #   - charmcraft
    #   - juju
    #   - rockcraft
    #   - lxd
    #   - snapcraft
    stage:
      - -etc/bash_completion.d
      - -etc/cron.d
      - -etc/depmod.d
      - -etc/ldap
      - -etc/logrotate.d
      - -etc/init.d
      - -etc/perl
      - -etc/rsyslog.d
      - -etc/sudoers.d
      - -lib/systemd/system
      - -usr/bin/perl*
      - -usr/include
      - -usr/lib/*/*perl*
      - -usr/share/bash-completion
      - -usr/share/doc
      - -usr/share/doc-base
      - -usr/share/info
      - -usr/share/initramfs-tools
      - -usr/share/lintian
      - -usr/share/man
      - -usr/share/nano
      - -usr/share/perl
      - -usr/share/perl5
      - -usr/share/zsh
